Friendship v2
abredi/ror-social-scaffold pull request #3
Opened 2020-09-17 18:15 UTC by abredi

add mutual friendship

2020-09-17 20:02 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
### Good job so far :+1: you have done a great job. However, you need to implement the following :point_down: requirements before this project can be approved.

- **_Enable linter._**

- **_Only the user's posts and their friends' posts should be visible to the user._**

**_Fix these and request another review._**

#### _Reviewed by Temitayo Adeleke_

2020-09-17 20:02 UTC, lekegitrepo commented on app/models/friendship.rb
>  end
- **_when friendship is confirmed, an additional row with reversed user-friend pair is created_**

2020-09-17 20:28 UTC, abredi commented on app/models/friendship.rb
>  end
I didn't design to be like that. When the friend request is confirmed, the status would be changed.

2020-09-17 20:35 UTC, abredi commented
I enabled the linter but, GitHub activates the linter when I create a pull request upon the main repo. If you can help me to initiate here(comparing with the forked repo branch), I appreciate that.

2020-09-18 01:20 UTC, christianotieno approved these changes
# PROJECT APPROVED 🍾 

Good job with the changes. Everything looks okay now. 

I am giving this a pass. All the best with the next tasks @abredi 🥇 

#### Christian Otieno (TSE)

2020-09-21 23:31 UTC, merged